### ISSUE TITLE
مرحباً اخي عبدالله.

### ISSUE THREAD

**Issue by fahad4x4** [abdullahmohsen/Backpack-Website#1]
السلام عليكم.
اخي عبدالله.
كيف اقوم بتركيبه على موقعي الشخصي من خلال cPanel

**Comment by abdullahmohsen** [comment]
راسلني علي الواتس اب +971586868890

**Comment by fahad4x4** [comment]
للاسف لا املك واتساب :)
Signal>>
Telegram>>

**Comment by abdullahmohsen** [comment]
+201063377370 
راسلني علي Telegram

**Comment by fahad4x4** [comment]
بالتوفيق.
